services:
  
  app:
    image: precifier-with-ollama:latest
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped
    ports:
      - "8002:8002"
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    networks:
      - app-network
  
volumes:
  ollama_data:
    name: ollama_data

networks:
  app-network:
    driver: bridge